# Your Name or Company
title: Alice Battiston

# Description of your website. This is used for social sharing.
description:  My name is Alice Battiston and I am a second-year PhD candidate in Modeling and Data Science at the University of Turin.

# A brief blurb about yourself
content: Hi all!<br> My name is Alice Battiston and I am a second-year PhD candidate in <a href="https://dottorato-mds.campusnet.unito.it/do/home.pl">Modeling and Data Science</a> at the University of Turin, working with <a href="http://www.di.unito.it/~schifane/">Prof. Rossano Schifanella</a>. <br> My research is at the intersection of computational social science, spatial analysis and the modeling of urban systems. I am interested in data-driven approaches to policy-making in urban environments, with a focus on enhancing the liveability and sustainability of our cities. <br> My background is in Economics and Statistics, which I studied in Turin <a href="https://en.unito.it/">@UniversityOfTurin</a> and <a href="https://www.carloalberto.org/">@CollegioCarloAlberto</a> and in London <a href="https://www.ucl.ac.uk/">@UniversityCollegeLondon</a> . <br> Before joining the academia again in 2020, I worked for three years as data analyst and economic consultant (<a href="https://londoneconomics.co.uk/">@LondonEconomics</a>, London, UK), specializing in applied micro-econometrics. 

# Add your social links
social:
  - platform: email
    url: mailto:ali.battistpn@gmail.com
  - platform: twitter
    url: https://twitter.com/AliBattiston
  - platform: linkedin
    url: https://it.linkedin.com/in/alice-battiston-783194118
  - platform: Github
    url: https://github.com/alibatti

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: assets/img/AliceBattiston.JPG
#google_analytics: "G-QJW8913FZV" # google analytics tracking

sass:
    sass_dir: ./assets/ccs

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
